---
title: "Assignment 1: Introduction"
author: "Michael Gaffney"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
I have worked with R in the 710 class here at the Nicholas School, and so I have some experience with it. In terms of git, I have worked with it before in advanced GIS. Both of those classes represent the extent of my knowledge of environmental data analytics (although I have also done some analysis for my MP).

2. Are there any components of the course about which you feel confident?

> Answer:
I feel relatively confident in my understanding of R, and in coding in general.

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
Although I understand the purpose and concept of Git, there do seem to be a few things that can go wrong with it.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/mtgaffney/Environmental_Data_Analytics_2022


